export const FETCH_MENTIONS_PENDING = 'NEXT-MENTION/MENTIONS/FETCH_MENTIONS_PENDING'
export const FETCH_MENTIONS_FAILURE = 'NEXT-MENTION/MENTIONS/FETCH_MENTIONS_FAILURE'
export const FETCH_MENTIONS_SUCCESS = 'NEXT-MENTION/MENTIONS/FETCH_MENTIONS_SUCCESS'
